### ISSUE TITLE
error[E0554]: #![feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by animanga** [nimiq/core-rs#18]
error[E0554]: #![feature] may not be used on the stable release channel
 --> collections/src/lib.rs:2:1
  |
2 | #![feature(box_into_raw_non_null)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> collections/src/lib.rs:3:1
  |
3 | #![feature(specialization)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> collections/src/lib.rs:4:1
  |
4 | #![feature(map_get_key_value)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling indexmap v1.0.2
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `nimiq-collections`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by animanga** [comment]
This issue coming when I am running cargo run and on cargo build too coming i am new to rust but i am trying build and run from source code ;) and hope i can somehow contribute ;)

**Comment by paberr** [comment]
The `nimiq-collections` crate requires using the nightly version of Rust.
You can use `rustup override set nightly` in the `core-rs` folder to switch your Rust version to nightly for this directory.
Then, it should work. 👍
